name: Example auto-fix generation
on: push
jobs:
  checks:
    runs-on: ubuntu-latest
    name: Checks
    steps:
      - uses: actions/checkout@v2
      - run: yarn
        if: always()
      - run: yarn --no-immutable
        if: always()
      - run: yarn lint
        if: always()
      - run: yarn test
        if: always()
      - run: yarn prettier --check .
        if: always()
