name: Example auto-fix generation
on: push
jobs:
  checks:
    runs-on: ubuntu-latest
    name: Checks
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn lint --fix
      - run: yarn test --updateSnapshot
      - run: yarn prettier --write .
      - uses: dtinth/patch-generator-action@main